### ISSUE TITLE
No Site Key or API key in REST request?

### ISSUE THREAD

**Issue by axon-obriend** [TechToThePeople/ldapcivi#6]
I'm trying to set this up to investigate for a couple of clients that this would be useful for. I've got all the pieces installed and (kind of) working. The request that gets sent to my CiviCRM instance (on Wordpress) seems not to have the Site Key or API key that were configured in the setup. They are configured and I a URL with the site key and API key works when it's entered in a browser.

Any thoughts?

**Comment by agh1** [comment]
Recently ran into this sort of thing--LDAP didn't work for a WordPress site, worked fine for another (Drupal) site. I then tried with a fresh dummy WordPress site, which worked perfectly.

With further examination, I found I could run REST API calls (Contact.get) just fine through cURL with `-G` (HTTP `GET`) but not without (HTTP `POST`). Nothing funky in the site's .htaccess, but it turns out the WP-SpamShield plugin was causing mayhem. I disabled it, and everything works great.
